### ISSUE TITLE
scrolling list is extremely laggy if mouse is hovering something

### ISSUE THREAD

**Issue by abenz1267** [hyprutils/hyprlauncher#151] opened 2024-12-05 04:48 UTC
https://github.com/user-attachments/assets/d6ca5c20-cbd4-41df-a938-decec6aa51c6

As you can see in this video, when the mouse is inside the list, scrolling becomes extremely laggy.

**Comment by nnyyxxxx** [comment] 2024-12-05 05:20
the scrolling is not laggy its just returning to the selected mouse entry

**Comment by nnyyxxxx** [comment] 2024-12-05 05:21
walker does the same thing

**Comment by abenz1267** [comment] 2024-12-05 05:22
https://github.com/user-attachments/assets/bdd3f9ff-0fe6-4a85-8c72-b86c58232639

Hm? Walker behaves smooth when the mouse is hovering inside the list when scrolling.

**Comment by nnyyxxxx** [comment] 2024-12-05 05:24
after each scroll it is returning to the mouse selected entry

**Comment by abenz1267** [comment] 2024-12-05 05:25
Yes, but obv. if you scroll using the keyboard, it shouldn't do that.

If you don't wanna fix that, don't fix that.

**Comment by abenz1267** [comment] 2024-12-05 05:27
![image](https://github.com/user-attachments/assets/e4046ed3-3ce4-489e-9fc0-2a3766d15ff9)

This is clearly an issue. I search "fire" and wanna open the top result and not have my mouse interfere with the selection.

**Comment by nnyyxxxx** [comment] 2024-12-05 05:30
not sure what the issue is, it doesnt look laggy to me

**Comment by nnyyxxxx** [comment] 2024-12-05 05:30
if it is related to this:
https://github.com/hyprutils/hyprlauncher/issues/147
then it will be fixed sooner or later

**Comment by abenz1267** [comment] 2024-12-05 05:32
This is not related to #147.


https://github.com/user-attachments/assets/f5b7a2c8-2411-464c-bd7d-dd9b0cb6d4ab

Here's a video showing how scrolling behaves when not having the mouse hovering vs. the hovering. Clearly this is bad behaviour and should be fixed.

**Closed** 2024-12-05 05:31 UTC
Labels: invalid

**Comment by nnyyxxxx** [comment] 2024-12-05 05:33
it's scrolling off of the mouse selected entry, walker does the same

**Comment by abenz1267** [comment] 2024-12-05 05:34
> it's scrolling off of the mouse selected entry, walker does the same

stop saying walker does the same when i literally just posted a video clearly showing it doesn't.

**Comment by nnyyxxxx** [comment] 2024-12-05 05:37
https://github.com/user-attachments/assets/2812f3ce-6efc-48b2-88f7-1ab4c9ca438f

it literally does

**Comment by abenz1267** [comment] 2024-12-05 05:37
https://github.com/user-attachments/assets/7b9df430-530b-4811-a0df-668d5b443961

Here's another video showing you one after another how Walker behaves correctly while Hyprlauncher doesn't.

**Comment by nnyyxxxx** [comment] 2024-12-05 05:40
> it literally does

^^^^^^^

**Comment by abenz1267** [comment] 2024-12-05 05:42
Even IF Walker would do the same: how does that change the fact HYPRLAUNCHER... this is the HYPRLAUNCHER repo.... shouldn't do that? Clownproject.
